accounts/urls.py
from django.urls import path
from .views import Logout, Register, Login, Profile, UpdateProfile, MesCommandes, MesFormations

app_name = 'accounts'

urlpatterns = [
    path('login/', Login, name='login'),
    path('register/', Register, name='register'),
    path('logout/', Logout, name='logout'),
    path('profile/<str:username>', Profile, name='profile'),
    path('update_profile/<int:pk>', UpdateProfile, name='update_profile'),
    path('commandes/', MesCommandes, name='commandes'),
    path('formations/', MesFormations, name='formations'),
]

back/urls.py
from django.urls import path
from .views import Dashboard, Users, Formations, Commandes, Emplois

app_name = 'back'

urlpatterns = [
    path('', Dashboard, name='dashboard'),
    path('users/', Users, name='users'),
    path('formations/', Formations, name='formations'),
    path('commandes/', Commandes, name='commandes'),
    path('emplois/', Emplois, name='emplois'),
]

home/urls.py
from django.urls import path
from .views import Home, Search, BigSearch, Etude_sol, EmploiList, DetailEmploi, Appel, assistance_emploi, Immobilier, AchatView, FormationList, DetailFormation, FollowFormation, UnfollowFormation, Contact, about

app_name = 'home'

urlpatterns = [
    path('', Home, name='home'),
    path('search/', Search, name='search'),
    path('searchs/', BigSearch, name='big-search'),
    path('etude_sol/', Etude_sol, name='etude_sol'),
    path('emploi/', EmploiList, name='emploi'),
    path('emploi_detail/<int:pk>/', DetailEmploi, name='detail_emploi'),
    path('appel_d_offre/', Appel, name='appel'),
    path('immobilier/', Immobilier, name='immobilier'),
    path('achat/', AchatView, name='achat'),
    path('assistance_emploi/', assistance_emploi, name='assistance_emploi'),
    path('formations/', FormationList, name='formation'),
    path('formation/<str:slug>/', DetailFormation, name='detail_formation'),
    path('Followformation/<str:slug>/', FollowFormation, name='follow_formation'),
    path('Unfollowformation/<str:slug>/', UnfollowFormation, name='unfollow_formation'),
    path('contact/', Contact, name='contact'),
    path('about/', about, name='about'),
]

strata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('back/', include('back.urls')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model

User = get_user_model()

class Subject(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Formation(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='formation/')
    description = models.TextField()
    avantage = models.TextField()
    certification = models.TextField()
    auteur = models.CharField(max_length=100)
    duree = models.CharField(max_length=100)
    prix = models.CharField(max_length=100)
    souscrire = models.ManyToManyField(User)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)



class Domaine(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Emploi(models.Model):
    domaine = models.ForeignKey(Domaine, on_delete=models.SET_NULL, null=True)
    poste = models.CharField(max_length=100)
    image = models.ImageField(upload_to='emploi/')
    entreprise = models.CharField(max_length=100)
    lieu = models.CharField(max_length=100)
    description = models.TextField()
    tache = models.TextField()
    competence = models.TextField()
    postuler = models.ManyToManyField(User)
    cloture = models.DateField()
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.poste



PATEFORME = (
    ('amazone', 'Amazone'),
    ('alibaba', 'Alibaba'),
    ('ebay', 'Ebay'),
)

LIVRAISON = (
    ('en cours', 'En cours'),
    ('livré', 'Livré'),
)

class Achat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plateforme = models.CharField(choices=PATEFORME, max_length=15)
    lien = models.CharField(max_length=300)
    adresse = models.CharField(max_length=200)
    livraison = models.CharField(choices=LIVRAISON, default='en cours', max_length=15)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.plateforme

home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.db.models import Q
from back.models import Subject, Formation, Domaine, Emploi, Achat
from back.forms import AchatForm


def Home(request):
    template_name = 'home/index.html'
    return render(request, template_name)

def Search(request):
    query = request.GET.get('q')
    emplois = Emploi.objects.filter(Q(poste__icontains=query) | Q(description__icontains=query))
    template_name = 'home/search.html'
    context = {
        'query': query,
        'emplois': emplois,
    }
    return render(request, template_name, context)

def BigSearch(request):
    query = request.GET.get('query')
    emplois = Emploi.objects.filter(Q(poste__icontains=query) | Q(description__icontains=query))
    formations = Formation.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
    template_name = 'home/big-search.html'
    context = {
        'query': query,
        'emplois': emplois,
        'formations': formations,
    }
    return render(request, template_name, context)

def Etude_sol(request):
    template_name = 'home/etude_sol.html'
    return render(request, template_name)


def EmploiList(request):
    domaines = Domaine.objects.all()
    emplois = Emploi.objects.all().order_by('-id')
    template_name = 'home/emploi.html'
    context = {
        'domaines': domaines,
        'emplois': emplois,
    }
    return render(request, template_name, context)

def DetailEmploi(request, pk):
    emploi = get_object_or_404(Emploi, pk=pk)
    domaines = Domaine.objects.all()
    template_name = 'home/detail_emploi.html'
    context = {
        'emploi': emploi,
        'domaines': domaines,
    }
    return render(request, template_name, context)


def Appel(request):
    template_name = 'home/appel.html'
    return render(request, template_name)

def assistance_emploi(request):
    template_name = 'home/assistance_emploi.html'
    return render(request, template_name)

def Immobilier(request):
    template_name = 'home/immobilier.html'
    return render(request, template_name)

def AchatView(request):
    user = request.user
    plateforme = request.POST.get('plateforme')
    lien = request.POST.get('lien')
    adresse = request.POST.get('adresse')
    if request.method=='POST':
        Achat.objects.create(user=user, plateforme=plateforme, lien=lien, adresse=adresse)
        messages.success(request, "Votre commande a été envoyé avec succès")
        return HttpResponseRedirect(reverse('home:achat'))
    else:
        return render(request, 'home/achat.html')


def FormationList(request):
    formations = Formation.objects.all().order_by('-date')
    template_name = 'home/formation.html'
    context = {
        'formations': formations,
    }
    return render(request, template_name, context)

def DetailFormation(request, slug):
    formation = get_object_or_404(Formation, slug=slug)
    template_name = 'home/detail_formation.html'
    context = {
        'formation': formation,
    }
    return render(request, template_name, context)


def FollowFormation(request, slug):
    user = request.user
    souscrire = False
    if request.method == 'POST':
        formation = Formation.objects.get(slug=slug)
        if user not in formation.souscrire.all():
            formation.souscrire.add(user)
            souscrire = True
            context = {
                'formation': formation,
                'souscrire': souscrire,
                'souscrire_number': formation.souscrire.count(),
                }
            return HttpResponseRedirect(reverse('home:detail_formation', args=[slug]))
    else:
        return render(request, 'home/formation.html')
    return render(request, template_name, context)


def UnfollowFormation(request, slug):
    user = request.user
    souscrire = True
    if request.method == 'POST':
        formation = Formation.objects.get(slug=slug)
        if user in formation.souscrire.all():
            formation.souscrire.remove(user)
            souscrire = False
            context = {
                'formation': formation,
                'souscrire': souscrire,
                'souscrire_number': formation.souscrire.count(),
                }
            return HttpResponseRedirect(reverse('home:detail_formation', args=[slug]))
    else:
        return render(request, 'home/formation.html')


def Contact(request):
    template_name = 'home/contact.html'
    return render(request, template_name)

def about(request):
    template_name = 'home/about.html'
    return render(request, template_name)
    

templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

    <head>
        {% include 'includes/css.html' %}
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        
        <!-- Navbar Start -->
        <div class="container-fluid">
            <nav class="navbar navbar-dark navbar-expand-xxl align-items-center">
                <div class="d-flex">
                    <a href="{% url 'home:home' %}" class="d-flex align-items-center navbar-brand ">
                        <img src="{% static 'img/logo.png' %}" style="width: 50px;" alt="">
                        <span style="font-size: 1rem; color: #255085; padding: 0px 7px; border-left: 2px solid #255085;" class="d-none d-md-inline">STRATA CONSULT</span>
                    </a>
                    <button class="navbar-toggler p-0" type="button" data-bs-toggle="collapse" id="navbarBtn" data-bs-target="#navbarCollapse" style="font-size: 0.95rem; border: 1px solid; border-left: 1px solid #bbb;">
                        &nbsp;&nbsp;<span class="fa fa-bars" style="color: #255085;">&nbsp; MENU</span> 
                    </button>
        
                    <div class="collapse navbar-collapse me-n3" id="navbarCollapse">
                        <div class="navbar-nav">
                            <div class="d-flex justify-content-between align-items-center px-2">
                                <h5>MENU</h5>
                                <button class="navbar-toggler p-0" type="button" data-bs-toggle="collapse"  id="navbarBtn" data-bs-target="#navbarCollapse">
                                    <span class="fa fa-times text-dark"></span>
                                </button>
                            </div>
                            <hr class="my-2 py-1">
                            <a href="{% url 'home:home' %}" class="nav-item nav-link active">Accueil</a>
                            <a href="{% url 'home:etude_sol' %}" class="nav-item nav-link">Geo-Strata</a>
                            <a href="{% url 'home:emploi' %}" class="nav-item nav-link">Strata-Emploi</a>
                            <a href="{% url 'home:immobilier' %}" class="nav-item nav-link">Strata-Immo</a>
                            <a href="{% url 'home:formation' %}" class="nav-item nav-link">Strata-Formation</a>
                            <a href="{% url 'home:achat' %}" class="nav-item nav-link">Facilitation achat en ligne</a>
                            <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact</a>
                            <a href="#footer" class="nav-item nav-link">A propos</a>
                        </div>
                    </div>
                </div>

                <div class="pub">
                    <div class="d-flex justify-content-center align-items-center" style="width: 500px; background-color: #ff5950;">
                        <h2 class="text-white m-0 py-2">VOTRE PUBLICITE</h2>
                    </div>
                </div>

                <div class="buttons d-flex">
                    <a href="#r" class="top-search-btn"><img src="{% static 'img/search.png' %}" alt=""> <span class="d-none d-md-inline">RECHERCHE</span></a> &nbsp;&nbsp;&nbsp;&nbsp;
                    {% if user.is_authenticated %}
                    <a href="{% url 'accounts:profile' request.user.username %}"><img src="{% static 'img/user.png' %}" alt=""> <span class="d-none d-md-inline">PROFILE</span></a> &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'accounts:logout' %}"><img src="{% static 'img/user.png' %}" alt=""> <span class="d-none d-md-inline">DECONNEXION</span></a>
                    {% if user.is_superuser %}
                    <a href="{% url 'back:dashboard' %}">&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static 'img/user.png' %}" alt=""> <span class="d-none d-md-inline">ADMIN</span></a>
                    {% endif %}
                    {% else %}
                    <a href="#login" class="login-btn d-flex"><img src="{% static 'img/user.png' %}" alt=""> <span class="d-none d-md-inline">CONNEXION</span></a> &nbsp;&nbsp;&nbsp;&nbsp;
                    {% endif %}
                </div>
            </nav>
        </div>
        <!-- Navbar End -->

        {% block content %}{% endblock %}



        <!-- Form Start -->
        <div id="myform" class="container-fluid form-hide mb-3">
            <div class="container">
                <div class="d-flex justify-content-between">
                    <span>.</span>
                    
                </div>
                <div class="row g-5 box animated slideInUp justify-content-between position-relative">
                    <div class="col-lg-6 d-none d-lg-block">
                    </div>
                    <div class="col-lg-6 form bg-white" data-wow-delay=".5s" style="border-radius: 10px; margin-top: 0px;;">
                        <img src="{% static 'img/close.png' %}" alt="" class="myform-btn close-btn" id="login-close">
                        <div class="py-2">
                            <h2 class="mb-4" style="color: #255085;">Formulaire</h2>
                        </div>
                        <form method="post" class="rounded contact-form mb-3">
                            {% csrf_token %}
                            <div class="mb-4">
                                <input type="text" class="form-control p-3" placeholder="Donnée" required>
                            </div>
                            <div class="mb-4">
                                <input type="text" class="form-control p-3" placeholder="Donnée" required>
                            </div>
                            <div class="mb-4">
                                <textarea class="form-control w-100" rows="10"></textarea>
                            </div>
                            <button class="btn btn-primary border-0 py-2 d-block w-100 mb-2" type="submit">Soumettre</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Form End -->


        <!-- SearchBar Start -->
        <div id="SearchBar" class="container-fluid form-hide">
            <div class="container">
                <div class="search mb-2 text-center">
                    <form action="{% url 'home:big-search' %}" method="get" class="w-100">
                        <input type="text" name="query" placeholder="Tapez votre recherche..." style="width: 88%; padding: 10px 80px 10px 10px;">
                        <button tupe="submit" style="width: 10%; padding: 10px 0px; background-color: #ff5950; color: #fff;"><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>
        <!-- SearchBar End -->


        <!-- Login Start -->
        <div id="login" class="container-fluid form-hide">
            <div class="container">
                <div class="d-flex justify-content-between">
                    <span>.</span>
                    
                </div>
                <div class="row g-5 box wow fadeInUp justify-content-between">
                    <div class="col-lg-6 d-none d-lg-block">
                    </div>
                    <div class="col-lg-6 form bg-white" data-wow-delay=".5s" style="border-radius: 10px;">
                        <img src="{% static 'img/close.png' %}" alt="" class="login-btn close-btn" id="login-close">
                        <div class="py-2">
                            <h2 class="mb-4 animated slideInDown" style="color: #255085;">Connectez-vous</h2>
                        </div>
                        <form method="post" action="{% url 'accounts:login' %}" class="rounded contact-form mb-3">
                            {% csrf_token %}
                            <div class="mb-4">
                                <input type="text" class="form-control p-3" name="username_email" placeholder="Identifiant" required>
                            </div>
                            <div class="mb-4">
                                <input type="password" class="form-control p-3" name="password" placeholder="Mot de passe" required>
                            </div>
                            <button class="btn btn-primary border-0 py-2 d-block w-100 mb-2" type="submit">Se connecter</button>
                            <p class="m-0 text-center">ou <a href="{% url 'accounts:register' %}"><small>S'enregistrer</small></a></p>
                            <hr>
                            <div class="text-center">
                                <small>Se connecter avec</small><br>
                                <button type="button" class="btn btn-danger d-block mt-2 w-100">Google</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Login End -->


        <!-- Footer Start -->
        <div id="footer" class="container-fluid footer py-5 wow fadeIn" data-wow-delay=".3s">
            <div class="container py-5">
                <div class="row justify-content-between g-4 footer-inner">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h4 class="text-white text-center fw-bold mb-4">A propos Strata.</h4>
                            <div class="text-center">
                                <small>Une entreprise dynamique, passionnée pour la recherche et l’innovation ; engager à apporter des solutions aux besoins de base des entreprises et des particuliers.</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h4 class="text-white fw-bold mb-4">Liens utiles</h4>
                            <div class="d-flex flex-column align-items-start">
                                <a class="btn btn-link ps-0" href=""><i class="fa fa-check me-2"></i>A propos de nous</a>
                                <a class="btn btn-link ps-0" href="{% url 'home:contact' %}"><i class="fa fa-check me-2"></i>Nous Contacter</a>
                                <a class="btn btn-link ps-0" href=""><i class="fa fa-check me-2"></i>Partenariat et affiliation</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h4 class="text-white fw-bold mb-4">Nos coordonnées</h4>
                            <a href="" class="btn btn-link w-100 text-start ps-0 pb-3 border-bottom rounded-0"><i class="fa fa-map-marker-alt me-3"></i>Kinshasa RDC</a>
                            <a href="" class="btn btn-link w-100 text-start ps-0 py-3 border-bottom rounded-0"><i class="fa fa-phone-alt me-3"></i>+000 000 000 000</a>
                            <a href="" class="btn btn-link w-100 text-start ps-0 py-3 border-bottom rounded-0"><i class="fa fa-envelope me-3"></i>infos@strata-consult.com</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Copyright Start -->
        <div class="container-fluid copyright py-4 text-white" style="background-color: #303944">
            <div class="container">
                <div class="row justify-content-center align-items-center">
                    <div class="col-md-4 text-center text-md-start mb-3 mb-md-0">
                        <span>© 2023 Strata Consult, Tout droit réservé</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- Copyright End -->

        {% include 'includes/scripts.html' %}
    </body>

</html>

templates/home/detail_formation.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %}Detail Formation{% endblock %}

{% block content %}

        <!-- Content Start -->
        <div class="container-fluid">
            <div class="container py-5">
                <div class="about-item overflow-hidden">
                    <h2 class="mb-3">Formation {{formation.title}}</h2>
                </div>
                <div class="row m-0 blog-item wow fadeInUp" data-wow-delay=".6s">
                    <div class="col-md-4 mb-2">
                        <img src="{{formation.image.url}}" class="rounded-top" alt="{{formation.title}}">
                        <h5 class="mt-3">Par : &nbsp; {{formation.auteur}}</h5>
                        <h5 class="mt-3">Durée : &nbsp; {{formation.duree}}</h5>
                        <h3 style="color: #255085; font-size: 4rem;">${{formation.prix}}</h3>
                        {% if request.user in formation.souscrire.all %}
                        <span style="border: 1px solid #222; background-color: #55a; color: #fff; padding: 5px 30px; border-radius: 15px;">Vous avez souscrit</span>
                        {% else %}
                        <form action="{% url 'home:follow_formation' formation.slug %}" method="post">
                            {% csrf_token %}
                            <button style="border: 1px solid #222; background-color: #222; color: #fff; padding: 5px 30px; border-radius: 15px;" type="submit">Souscrire</button>
                        </form>
                        {% endif %}
                    </div>
                    <div class="col-md-8 mb-3">
                        <div class="px-4 pb-0 py-2">
                            <h5>Description</h5>
                            {{formation.description}}
                            
                            <h5 class="mt-4">Avantages</h5>
                            {{formation.avantage}}
                            
                            <h5 class="mt-4">Certification</h5>
                            {{formation.certification}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Content End -->

{% endblock %}

templates/home/emploi.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %}Ressources humaines, emploi et opportunités{% endblock %}

{% block content %}


        <!-- Page Header Start -->
        <div class="container-fluid p-0" style="background-image: url({% static 'img/img6.jpg' %}); background-size: cover; margin-bottom: 6rem;;">
            <div style="padding: 100px 5%; background-color: rgba(0, 0, 0, 0.3);">
                <h3 class="text-white mb-4 px-2 py-3 text-center animated slideInDown">Strata-Emploi</h3>
                <form method="post" class="wish-form">
                    {% csrf_token %}
                    <select name="who">
                        <option value="-----" disabled selected>Vous êtes</option>
                        <option value="particulier">Particulier</option>
                        <option value="entreprise">Entreprise</option>
                    </select>
                    <select name="wish">
                        <option value="-----" disabled selected>Vous voulez</option>
                        <option value="devis">Avoir un devis</option>
                        <option value="partenaire">Créer un compte partenaire</option>
                    </select>
                    <input type="text" placeholder="Localisation">
                    <button type="submit" class="bg-primary text-white">Votre solution</button>
                </form>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Blog Start -->
        <div class="container-fluid">
            <div class="container pb-5">
                <div class="row justify-content-center m-0 box">
                    <div class="col-lg-10 items">
                        <div class="d-flex title">
                            <h5 class="mb-"><a href="{% url 'home:emploi' %}" class="active">Offres d'emploi</a></h5>
                            <h5 class="mb-2"><a href="{% url 'home:appel' %}" class="">Appel d'offre</a></h5>
                            <h5 class="mb-2"><a href="{% url 'home:assistance_emploi' %}" class="">Assistance emploi</a></h5>
                        </div>
                        <hr class="mt-0">
                        {% for emploi in emplois %}
                        <div class="row m-0 detail wow fadeInUp mb-3" data-wow-delay=".6s">
                            <div class="col-4 p-0">
                                <img src="{{emploi.image.url}}" alt="{{emploi.poste}}">
                            </div>
                            <div class="col-8 content">
                                <h5><a href="{% url 'home:detail_emploi' emploi.pk %}">{{emploi.poste}}</a></h5>
                                <p class="m-0 py-2">{{emploi.description}}</p>
                            </div>
                        </div>
                        <hr class="my-2">
                        {% endfor %}
                        <br>
                        <h5>Main d'oeuvre</h5>
                        <button class="btn btn-primary">Soumettre une main d'oeuvre</button> ou soit <button class="btn btn-primary">Demander une main d'oeuvre</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Blog End -->

{% endblock %}

templates/home/search.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %}Recherche - {{query}}{% endblock %}

{% block content %}


        <!-- Page Header Start -->
        <div class="container-fluid p-0" style="background-image: url({% static 'img/img6.jpg' %}); background-size: cover; margin-bottom: 6rem;;">
            <div style="padding: 100px 5%; background-color: rgba(0, 0, 0, 0.3);">
                <h3 class="text-white mb-4 px-2 py-3 text-center animated slideInDown">Recherche pour <strong>{{query}}</strong></h3>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Blog Start -->
        <div class="container-fluid">
            <div class="container pb-5">
                <div class="row m-0 box">
                    {% if emplois %}
                    <div class="col-lg-8 items">
                        <div class="d-flex title">
                            <h5 class="mb-"><a href="{% url 'home:emploi' %}" class="active">Offres d'emploi</a></h5>
                            <h5 class="mb-2"><a href="{% url 'home:appel' %}" class="">Appel d'offre</a></h5>
                            <h5 class="mb-2"><a href="{% url 'home:assistance_emploi' %}" class="">Assistance emploi</a></h5>
                        </div>
                        <hr class="mt-0">
                        {% for emploi in emplois %}
                        <div class="row m-0 detail wow fadeInUp mb-3" data-wow-delay=".6s">
                            <div class="col-4 p-0">
                                <img src="{{emploi.image.url}}" alt="{{emploi.poste}}">
                            </div>
                            <div class="col-8 content">
                                <h5><a href="{% url 'home:detail_emploi' emploi.pk %}">{{emploi.poste}}</a></h5>
                                <p class="m-0 py-2">{{emploi.description}}</p>
                            </div>
                        </div>
                        <hr class="my-2">
                        {% endfor %}
                    </div>
                    {% else %}
                    <h1 class="text-muted">Aucun emploi pour <strong>{{query}}</strong></h1>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Blog End -->

{% endblock %}