accounts/urls.py
from django.urls import path
from .views import Logout, Register, Login, Profile, UpdateProfile, MesCommandes, MesFormations

app_name = 'accounts'

urlpatterns = [
    path('login/', Login, name='login'),
    path('register/', Register, name='register'),
    path('logout/', Logout, name='logout'),
    path('profile/<str:username>', Profile, name='profile'),
    path('update_profile/<int:pk>', UpdateProfile, name='update_profile'),
    path('commandes/', MesCommandes, name='commandes'),
    path('formations/', MesFormations, name='formations'),
]

back/urls.py
from django.urls import path
from .views import Dashboard, Users, Formations, Commandes, Emplois

app_name = 'back'

urlpatterns = [
    path('', Dashboard, name='dashboard'),
    path('users/', Users, name='users'),
    path('formations/', Formations, name='formations'),
    path('commandes/', Commandes, name='commandes'),
    path('emplois/', Emplois, name='emplois'),
]

strata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('back/', include('back.urls')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager

GENDER = (
    ('M', 'M'),
    ('F', 'F'),
)

PROFILE = (
    ('Consommateur', 'Consommateur'),
    ('Ambassadeur', 'Ambassadeur'),
    ('Partenaire', 'Partenaire'),
)

class CustomUser(AbstractUser):
    full_name = models.CharField(('full_name'), max_length=50)
    email = models.EmailField(('email'), unique=True)
    phone = models.CharField(('phone'), max_length=15)
    birthday = models.DateField(('birthday'),)
    gender = models.CharField(('gender'), choices=GENDER, max_length=1)
    profile = models.CharField(('profile'), choices=PROFILE, max_length=15)

    objects = UserManager()

    def __str__(self):
        return f'{self.username}'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'full_name', 'email', 'phone', 'gender', 'birthday', 'profile', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control p-3', 'placeholder': "Nom d'utilisateur"}),
            'full_name': forms.TextInput(attrs={'class': 'form-control p-3', 'placeholder': "Nom complet"}),
            'email': forms.TextInput(attrs={'class': 'form-control p-3', 'placeholder': 'Email'}),
            'birthday': forms.DateInput(attrs={'class': 'form-control p-3', 'placeholder': 'Date de naissance. Format: JJ/MM/AA'}),
            'phone': forms.TextInput(attrs={'class': 'form-control p-3', 'placeholder': 'Téléphone'}),
            'gender': forms.Select(attrs={'class': 'form-control p-3'}),
            'profile': forms.Select(attrs={'class': 'form-control p-3'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control p-3', 'placeholder': 'Mot de passe'}),
        }
        

accounts/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import logout, login, authenticate
from django.contrib import messages
from .forms import UserUpdateForm
from django.contrib.auth.decorators import login_required
from back.models import Formation, Emploi, Achat
from django.contrib.auth import get_user_model


User = get_user_model()


def Register(request):
    template_name = 'accounts/register.html'
    if request.method == "POST":
        form = UserUpdateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        else:
            messages.error(request, "Données incorrectes! Réessayez")
            form = UserUpdateForm()
            context = {
                'form': form,
            }
            return render(request, template_name, context)
    form = UserUpdateForm()
    context = {
        'form': form,
    }
    return render(request, template_name, context)


def Login(request):
    username_email = request.POST.get('username_email')
    password = request.POST.get('password')
    if request.method=='POST':
        if(User.objects.filter(username=username_email).exists()):
            user = authenticate(username=username_email, password=password)
        elif(User.objects.filter(email=username_email).exists()):
            user = User.objects.get(email=username_email)
            user = authenticate(username=user.username, password=password)
        else:
            messages.error(request, "Données incorrects! Réessayez")
            return redirect('home:home')
        if user is not None:
            login(request, user)
            return redirect('home:home')
        else:
            messages.error(request, "Mot de passe incorrects! Réessayez")
            return redirect('home:home')
    else:
        return render(request, 'home/index.html')


def Logout(request):
    logout(request)
    return redirect('home:home')


@login_required
def Profile(request, username):
    user = get_object_or_404(User, username=username)
    context = { 
        'user': user,
        }
    return render(request, 'accounts/profile.html', context)


@login_required
def UpdateProfile(request, pk):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('accounts:profile', args=[pk]))
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, 'accounts/update_profile.html', {'form': form})
    

@login_required
def MesFormations(request):
    current_user = request.user
    formations = current_user.formation_set.all()
    template_name = 'accounts/formations.html'
    context = {
        'formations': formations,
    }
    return render(request, template_name, context)


@login_required
def MesCommandes(request):
    current_user = request.user
    commandes = Achat.objects.filter(user=current_user, livraison='en cours')
    template_name = 'accounts/commandes.html'
    context = {
        'commandes': commandes,
    }
    return render(request, template_name, context)
    

templates/accounts/base_profile.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}

        {% if user.is_authenticated %}
        <!-- Blog Start -->
        <div class="container-fluid p-0 dash h-100">
            <div class="row m-0 h-100">
                <div class="col-md-3 menu h-100">
                    <ul class="list-group">
                        <li class="list-group-item"><a href="#" class="active">Profile</a></li>
                        <li class="list-group-item"><a href="{% url 'accounts:commandes' %}">Mes commandes</a></li>
                        <li class="list-group-item"><a href="{% url 'accounts:formations' %}">Mes formations</a></li>
                        <li class="list-group-item"><a href="#">Offres d'emplois</a></li>
                        <li class="list-group-item"><a href="#">Affiliation</a></li>
                        <li class="list-group-item"><a href="#">Partenariat</a></li>
                        <li class="list-group-item"><a href="#">Paramètres</a></li>
                    </ul>
                </div>
                <div class="col-md-9 content">
                    {% block profile %}{% endblock %}
                </div>
            </div>
        </div>
        <!-- Blog End -->
        {% else %}
        <h1 class="text-center p-5">Veillez vous connecter pour acceder à cette page</h1>
        {% endif %}

{% endblock %}

templates/accounts/commandes.html
{% extends 'accounts/base_profile.html' %}

{% load static %}

{% block title %}Profile{% endblock %}

{% block profile %}

<div class="container pb-5">
    <div class="overflow-hidden">
        <h4 class="mb-4">Mes Commandes</h4>
    </div>
    {% if commandes %}
    <div class="table-responsive">
        <table class="table border">
            <thead>
                <th class="pb-3">Plateforme</th>
                <th class="pb-3">Lien</th>
                <th class="pb-3">Adresse</th>
                <th class="pb-3">Livraison</th>
                <th class="pb-3">Date</th>
            </thead>
            {% for commande in commandes %}
            <tr>
                <td class="pb-3">{{commande.plateforme}}</td>
                <td class="pb-3">{{commande.lien}}</td>
                <td class="pb-3">{{commande.adresse}}</td>
                <td class="pb-3">{{commande.livraison}}</td>
                <td class="pb-3">{{commande.date}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    <h5 class="text-muted">Vous n'avez aucune commandes en cours</h5>
    {% endif %}
</div>

{% endblock %}

templates/accounts/formations.html
{% extends 'accounts/base_profile.html' %}

{% load static %}

{% block title %}Profile{% endblock %}

{% block profile %}

                    <div class="container pb-5">
                        <div class="overflow-hidden">
                            <h5 class="mb-4">Mes formations</h5>
                        </div>
                        {% if formations %}
                        {% for formation in formations %}
                        <div class="row m-0">
                            <div class="col-lg-4 col-md-6 mb-3 blog-item wow fadeInUp" data-wow-delay=".6s">
                                <img src="{{formation.image.url}}" class="rounded-top" alt="{{formation.title}}">
                                 <div class="rounded-bottom bg-light">
                                    <div class="px-4 pb-0 py-2">
                                        <h5>{{formation.title}}</h5>
                                        <span>Par : {{formation.auteur}}</span> <br>
                                        <span>Durée : {{formation.duree}}</span>
                                    </div>
                                    <hr>
                                    <div class="p-4 py-2 text-center blog-btn">
                                        <a href="" type="button" class="text-dark">Détails</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <h4 class="text-muted">Vous n'avez souscrit à aucune formation</h4>
                        {% endif %}
                    </div>

{% endblock %}

templates/accounts/profile.html
{% extends 'accounts/base_profile.html' %}

{% load static %}

{% block title %}Profile{% endblock %}

{% block profile %}

                    <div class="container pb-5">
                        <div class="overflow-hidden">
                            <h5 class="mb-4">Informations du profile</h5>
                        </div>
                        <div class="row m-0 box">
                            <div class="col-12 items">
                                <table>
                                    <tr>
                                        <td class="pb-3">Identifiant</td>
                                        <td class="pb-3">&nbsp;&nbsp;&nbsp;&nbsp; {{request.user.username}}</td>
                                    </tr>
                                    <tr>
                                        <td class="pb-3">Nom complet</td>
                                        <td class="pb-3">&nbsp;&nbsp;&nbsp;&nbsp; {{request.user.full_name}}</td>
                                    </tr>
                                    <tr>
                                        <td class="pb-3">Genre</td>
                                        <td class="pb-3">&nbsp;&nbsp;&nbsp;&nbsp; {{request.user.gender}}</td>
                                    </tr>
                                    <tr>
                                        <td class="pb-3">Date de naissance</td>
                                        <td class="pb-3">&nbsp;&nbsp;&nbsp;&nbsp; {{request.user.birthday}}</td>
                                    </tr>
                                    <tr>
                                        <td class="pb-3">Téléphone</td>
                                        <td class="pb-3">&nbsp;&nbsp;&nbsp;&nbsp; {{request.user.phone}}</td>
                                    </tr>
                                    <tr>
                                        <td class="pb-3">Email</td>
                                        <td class="pb-3">&nbsp;&nbsp;&nbsp;&nbsp; {{request.user.email}}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>

{% endblock %}

templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

    <head>
        {% include 'includes/css.html' %}
        <title>Inscription</title>
    </head>

    <body style="background-image: url({% static 'img/logo.png' %}); background-repeat: no-repeat; background-size: contain;">
        
        <!-- Register Start -->
        <div class="container-fluid p-3" style="background: rgba(0, 0, 0, .5); position: relative;">
            <div class="container">
                <div class="row g-5 box wow fadeInUp justify-content-between py-3">
                    <div class="col-lg-6 d-none d-lg-block">
                    </div>
                    <div class="col-lg-6 form bg-white" data-wow-delay=".5s" style="border-radius: 10px;">
                        <div class="py-2">
                            <h2 class="mb-4 animated slideInDown" style="color: #255085;">Enregistrez-vous</h2>
                            {% if messages %}
                                {% for message in messages %}
                                    <span class="alert alert-danger">{{message}}</span>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <form method="post" class="rounded contact-form mb-3">
                            {% csrf_token %}
                            <div class="mb-4">
                                {{form.full_name}}
                            </div>
                            <div class="mb-4">
                                <select name="gender" class="form-control p-3" required="" id="id_gender">
                                    <option value="" selected disabled>Genre</option>
                                  
                                    <option value="M">M</option>
                                  
                                    <option value="F">F</option>
                                  
                                </select>
                            </div>
                            <div class="mb-4">
                                {{form.birthday}}
                            </div>
                            <div class="mb-4">
                                <select name="profile" class="form-control p-3" required="" id="id_profile">
                                    <option value="" selected disabled>Votre profile</option>
                                  
                                    <option value="Consommateur">Consommateur</option>
                                  
                                    <option value="Ambassadeur">Ambassadeur</option>
                                  
                                    <option value="Partenaire">Partenaire</option>
                                  
                                  </select>
                            </div>
                            <div class="mb-4">
                                {{form.phone}}
                            </div>
                            <div class="mb-4">
                                {{form.email}}
                            </div>
                            <div class="mb-4">
                                {{form.username}}
                            </div>
                            <div class="mb-4">
                                {{form.password}}
                            </div>
                            <button class="btn btn-primary border-0 py-2 px-3 d-block w-100 text-center mb-1" type="submit">S'enregistrer</button>
                            <p class="text-center">
                                ou <a href="#login" class="login-btn"><small>Se connecter</small></a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Register End -->

        <!-- Login Start -->
        <div id="login" class="container-fluid form-hide">
            <div class="container">
                <div class="d-flex justify-content-between">
                    <span>.</span>
                </div>
                <div class="row g-5 box wow fadeInUp justify-content-between">
                    <div class="col-lg-6 d-none d-lg-block">
                    </div>
                    <div class="col-lg-6 form bg-white" data-wow-delay=".5s" style="border-radius: 10px;">
                        <img src="img/close.png" alt="" class="login-btn" id="login-close">
                        <div class="py-2">
                            <h2 class="mb-4 animated slideInDown" style="color: #255085;">Connectez-vous</h2>
                        </div>
                        <form method="post" class="rounded contact-form mb-3">
                            <div class="mb-4">
                                <input type="text" class="form-control p-3" placeholder="Identifiant" required>
                            </div>
                            <div class="mb-4">
                                <input type="password" class="form-control p-3" placeholder="Mot de passe" required>
                            </div>
                            <button class="btn btn-primary border-0 py-2 px-3 rounded-pill" type="submit">Se connecter</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Login End -->
        
        {% include 'includes/scripts.html' %}
    </body>

</html>