back/urls.py
from django.urls import path
from .views import Dashboard, Users, Formations, Commandes, Emplois

app_name = 'back'

urlpatterns = [
    path('', Dashboard, name='dashboard'),
    path('users/', Users, name='users'),
    path('formations/', Formations, name='formations'),
    path('commandes/', Commandes, name='commandes'),
    path('emplois/', Emplois, name='emplois'),
]

strata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('back/', include('back.urls')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model

User = get_user_model()

class Subject(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Formation(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='formation/')
    description = models.TextField()
    avantage = models.TextField()
    certification = models.TextField()
    auteur = models.CharField(max_length=100)
    duree = models.CharField(max_length=100)
    prix = models.CharField(max_length=100)
    souscrire = models.ManyToManyField(User)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)



class Domaine(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Emploi(models.Model):
    domaine = models.ForeignKey(Domaine, on_delete=models.SET_NULL, null=True)
    poste = models.CharField(max_length=100)
    image = models.ImageField(upload_to='emploi/')
    entreprise = models.CharField(max_length=100)
    lieu = models.CharField(max_length=100)
    description = models.TextField()
    tache = models.TextField()
    competence = models.TextField()
    postuler = models.ManyToManyField(User)
    cloture = models.DateField()
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.poste



PATEFORME = (
    ('amazone', 'Amazone'),
    ('alibaba', 'Alibaba'),
    ('ebay', 'Ebay'),
)

LIVRAISON = (
    ('en cours', 'En cours'),
    ('livré', 'Livré'),
)

class Achat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plateforme = models.CharField(choices=PATEFORME, max_length=15)
    lien = models.CharField(max_length=300)
    adresse = models.CharField(max_length=200)
    livraison = models.CharField(choices=LIVRAISON, default='en cours', max_length=15)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.plateforme

back/forms.py
from django import forms
from .models import Achat


class AchatForm(forms.ModelForm):
    class Meta:
        model = Achat
        fields = ['plateforme', 'lien', 'adresse']
        widgets = {
            'plateforme': forms.Select(attrs={'class': 'form-control p-3'}),
            'lien': forms.TextInput(attrs={'class': 'form-control p-3', 'placeholder': "Inserez le lien de l'article"}),
            'adresse': forms.TextInput(attrs={'class': 'form-control p-3', 'placeholder': "Inserez l'adresse de livraison"}),
        }
        

back/views.py
from django.shortcuts import render
from accounts.models import CustomUser
from back.models import Subject, Formation, Domaine, Emploi, Achat
# from back.models import Subject, Formation, Domaine, Emploi
from django.contrib.auth import get_user_model

User = get_user_model()

def Dashboard(request):
    users = User.objects.all()
    subjects = Subject.objects.all()
    formations = Formation.objects.all()
    domaines = Domaine.objects.all()
    emplois = Emploi.objects.all()
    commandes = Achat.objects.all()
    template_name = 'back/dashboard.html'
    context = {
        'users': users.count(),
        'subjects': subjects.count(),
        'formations': formations.count(),
        'domaines': domaines.count(),
        'emplois': emplois.count(),
        'commandes': commandes.count(),
    }
    return render(request, template_name, context)


def Users(request):
    users = User.objects.all().order_by('id')
    template_name = 'back/users.html'
    context = {
        'users': users,
    }
    return render(request, template_name, context)


def Formations(request):
    subjects = Subject.objects.all().order_by('id')
    formations = Formation.objects.all().order_by('id')
    template_name = 'back/formations.html'
    context = {
        'subjects': subjects,
        'formations': formations,
    }
    return render(request, template_name, context)


def Commandes(request):
    commandes = Achat.objects.all().order_by('id')
    template_name = 'back/commandes.html'
    context = {
        'commandes': commandes,
    }
    return render(request, template_name, context)


def Emplois(request):
    emplois = Emploi.objects.all().order_by('id')
    template_name = 'back/emplois.html'
    context = {
        'emplois': emplois,
    }
    return render(request, template_name, context)

templates/back/base.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}

        {% if user.is_authenticated %}
        <!-- Blog Start -->
        <div class="container-fluid p-0 dash h-100">
            <div class="row m-0 h-100">
                <div class="col-md-3 menu h-100">
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{% url 'back:dashboard' %}" class="active">Dashboard</a></li>
                        <li class="list-group-item"><a href="{% url 'back:users' %}">Utilisateurs</a></li>
                        <li class="list-group-item"><a href="{% url 'back:formations' %}">Formations</a></li>
                        <li class="list-group-item"><a href="{% url 'back:commandes' %}">Commandes</a></li>
                        <li class="list-group-item"><a href="{% url 'back:emplois' %}">Offres d'emplois</a></li>
                        <li class="list-group-item"><a href="#">Affiliation</a></li>
                        <li class="list-group-item"><a href="#">Partenariat</a></li>
                        <li class="list-group-item"><a href="#">Paramètres</a></li>
                    </ul>
                </div>
                <div class="col-md-9 content">
                    {% block admin %}{% endblock %}
                </div>
            </div>
        </div>
        <!-- Blog End -->
        {% else %}
        <h1 class="text-center p-5">Veillez vous connecter pour acceder à cette page</h1>
        {% endif %}

{% endblock %}

templates/back/commandes.html
{% extends 'back/base.html' %}

{% load static %}

{% block title %}Formations{% endblock %}

{% block admin %}

<div class="container pb-5">
    <div class="overflow-hidden">
        <h4 class="mb-4">Mes Commandes</h4>
    </div>
    {% if commandes %}
    <div class="table-responsive">
        <table class="table border">
            <thead>
                <th class="pb-3">Utilisateur</th>
                <th class="pb-3">Plateforme</th>
                <th class="pb-3">Lien</th>
                <th class="pb-3">Adresse</th>
                <th class="pb-3">Livraison</th>
                <th class="pb-3">Date</th>
            </thead>
            {% for commande in commandes %}
            <tr>
                <td class="pb-3">{{commande.user.username}}</td>
                <td class="pb-3">{{commande.plateforme}}</td>
                <td class="pb-3">{{commande.lien}}</td>
                <td class="pb-3">{{commande.adresse}}</td>
                <td class="pb-3">{{commande.livraison}}</td>
                <td class="pb-3">{{commande.date}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    <h5 class="text-muted">Il n'y a aucune commandes en cours</h5>
    {% endif %}
</div>

{% endblock %}

templates/back/dashboard.html
{% extends 'back/base.html' %}

{% load static %}

{% block title %}Administration{% endblock %}

{% block admin %}

                    <div class="container pb-5">
                        <div class="overflow-hidden">
                            <h3 class="mb-4">Tableau de bord</h3>
                        </div>
                        <div class="row m-0 box">
                            <div class="col-md-6 col-lg-4 mb-2">
                                <div class="text-center bg-primary rounded p-3">
                                    <h5 class="text-white">Utilisateurs</h5>
                                    <h2 class="text-white">{{users}}</h2>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-4 mb-2">
                                <div class="text-center bg-danger rounded p-3">
                                    <h5 class="text-white">Formations</h5>
                                    <h2 class="text-white">{{formations}}</h2>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-4 mb-2">
                                <div class="text-center bg-warning rounded p-3">
                                    <h5 class="text-white">Commandes</h5>
                                    <h2 class="text-white">{{commandes}}</h2>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-4 mb-2">
                                <div class="text-center bg-info rounded p-3">
                                    <h5 class="text-white">Offres d'emploi</h5>
                                    <h2 class="text-white">{{emplois}}</h2>
                                </div>
                            </div>
                        </div>
                    </div>

{% endblock %}

templates/back/emplois.html
{% extends 'back/base.html' %}

{% load static %}

{% block title %}Formations{% endblock %}

{% block admin %}

                    <div class="container pb-5">
                        <div class="overflow-hidden">
                            <h3 class="mb-4">Formations</h3>
                        </div>
                        <div class="table-responsive">
                            <table class="table border">
                                <thead>
                                    <th class="pb-3">Image</th>
                                    <th class="pb-3">Poste</th>
                                    <th class="pb-3">Domaine</th>
                                    <th class="pb-3">Auteur</th>
                                    <th class="pb-3">Lieu</th>
                                    <th class="pb-3">Tâche</th>
                                    <th class="pb-3">Competences</th>
                                    <th class="pb-3">Description</th>
                                    <th class="pb-3">Membres</th>
                                    <th class="pb-3">Clôture</th>
                                    <th class="pb-3">Publié le</th>
                                </thead>
                                {% for emploi in emplois %}
                                <tr>
                                    <td class="pb-3"><img src="{{emploi.image.url}}" alt="{{emploi.title}}" style="width: 50px; height: 50px; object-fit: cover;"></td>
                                    <td class="pb-3">{{emploi.poste}}</td>
                                    <td class="pb-3">{{emploi.domaine}}</td>
                                    <td class="pb-3">{{emploi.entreprise}}</td>
                                    <td class="pb-3">{{emploi.lieu}}</td>
                                    <td class="pb-3" style="min-width: 150px;">{{emploi.tache|safe|truncatewords:10}}</td>
                                    <td class="pb-3" style="min-width: 150px;">{{emploi.competence|safe|truncatewords:10}}</td>
                                    <td class="pb-3" style="min-width: 150px;">{{emploi.description|safe|truncatewords:10}}</td>
                                    <td class="pb-3">
                                        {% if emploi.postuler.all %}
                                        {% for item in emploi.postuler.all %}
                                            {{item}}
                                        {% endfor %}
                                        {% else %}
                                            Aucun pour l'instant
                                        {% endif %}
                                    </td>
                                    <td class="pb-3">{{emploi.cloture}}</td>
                                    <td class="pb-3">{{emploi.date}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>

{% endblock %}

templates/back/formations.html
{% extends 'back/base.html' %}

{% load static %}

{% block title %}Formations{% endblock %}

{% block admin %}

                    <div class="container pb-5">
                        <div class="overflow-hidden">
                            <h3 class="mb-4">Formations</h3>
                        </div>
                        <div class="table-responsive">
                            <table class="table border">
                                <thead>
                                    <th class="pb-3">Image</th>
                                    <th class="pb-3">Titre</th>
                                    <th class="pb-3">Sujet</th>
                                    <th class="pb-3">Auteur</th>
                                    <th class="pb-3">Durée</th>
                                    <th class="pb-3">Coût</th>
                                    <th class="pb-3">Date</th>
                                </thead>
                                {% for formation in formations %}
                                <tr>
                                    <td class="pb-3"><img src="{{formation.image.url}}" alt="{{formation.title}}" style="width: 50px; height: 50px; object-fit: cover;"></td>
                                    <td class="pb-3">{{formation.title}}</td>
                                    <td class="pb-3">{{formation.subject.title}}</td>
                                    <td class="pb-3">{{formation.auteur}}</td>
                                    <td class="pb-3">{{formation.duree}}</td>
                                    <td class="pb-3">{{formation.prix}}</td>
                                    <td class="pb-3">{{formation.date}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>

{% endblock %}

templates/back/users.html
{% extends 'back/base.html' %}

{% load static %}

{% block title %}Utilisateurs{% endblock %}

{% block admin %}

                    <div class="container pb-5">
                        <div class="overflow-hidden">
                            <h3 class="mb-4">Utilisateurs</h3>
                        </div>
                        <div class="table-responsive">
                            <table class="table border">
                                <thead>
                                    <th class="pb-3">Identifiant</th>
                                    <th class="pb-3">Nom complet</th>
                                    <th class="pb-3">Email</th>
                                    <th class="pb-3">Téléphone</th>
                                    <th class="pb-3">Genre</th>
                                    <th class="pb-3">Profile</th>
                                    <th class="pb-3">Date</th>
                                </thead>
                                {% for user in users %}
                                <tr>
                                    <td class="pb-3">{{user.username}}</td>
                                    <td class="pb-3">{{user.full_name}}</td>
                                    <td class="pb-3">{{user.email}}</td>
                                    <td class="pb-3">{{user.phone}}</td>
                                    <td class="pb-3">{{user.gender}}</td>
                                    <td class="pb-3">{{user.profile}}</td>
                                    <td class="pb-3">{{user.date_joined}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>

{% endblock %}